name = "openid-provider-api-by-hono"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-02"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "kv-store"
id = "464f88835dc545778c62e25b0f5c9519"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "openid-provider"
database_id = "54dc7d05-7877-4c9e-b633-137bfc5ccf73"

# [ai]
# binding = "AI"

[observability.logs]
enabled = true

[vars]
ISSUER_URL = "https://identity-provider-by-next-js.vercel.app/"