# name: Deploy to Cloudflare Workers

# on:
#   push:
#     branches:
#       - main
# defaults:
#   run:
#     shell: bash

# jobs:
#   rewireDb:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Deploy to Cloudflare Workers
#         env:
#           DATABASE_ID: ${{ secrets.CLOUDFLARE_DATABASE_ID }}
#           DATABASE_NAME: ${{ secrets.CLOUDFLARE_DATABASE_NAME }}
#         run: |
#           # wrangler.tomlの環境変数を置換する場合
#           sed -i "s/DATABASE_ID/${DATABASE_ID}/g" wrangler.toml
#           sed -i "s/DATABASE_NAME/${DATABASE_NAME}/g" wrangler.toml
#       - uses: actions/upload-artifact@v4
#         with:
#           name: uploaded-wrangler
#           path: wrangler.toml
#           retention-days: 1

#   migrateDb:
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
#     needs: rewireDb
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/download-artifact@v4
#         with:
#           name: uploaded-wrangler
#           path: ./
#       - uses: actions/setup-node@v4
#         with:
#           node-version: "20"
#       - run: |
#           npm install -g wrangler
#           wrangler d1 migrations apply ${DATABASE_NAME} --remote
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_MIGRATION_D1_API_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           DATABASE_NAME: ${{ secrets.CLOUDFLARE_DATABASE_NAME }}

#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
#     needs: migrateDb
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/download-artifact@v4
#         with:
#           name: uploaded-wrangler
#           path: ./
#       - name: Build & Deploy Worker
#         uses: cloudflare/wrangler-action@v3
#         env:
#           API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#         with:
#           apiToken: ${{ env.API_TOKEN }}
#           accountId: ${{ env.ACCOUNT_ID }}
